# This file was generated by GoReleaser. DO NOT EDIT.
cask "logf" do
  name "logf"
  desc "Interactive JSON log viewer for the terminal"
  homepage "https://github.com/Johannes-Krabbe/logf"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logf"

  on_macos do
    on_intel do
      url "https://github.com/Johannes-Krabbe/logf/releases/download/v#{version}/logf_#{version}_darwin_amd64.tar.gz"
      sha256 "ba72a098a48498d2dd3988e07055d44b8199e9fc1caa78cef4eb37168e302018"
    end
    on_arm do
      url "https://github.com/Johannes-Krabbe/logf/releases/download/v#{version}/logf_#{version}_darwin_arm64.tar.gz"
      sha256 "ca49e9a11e22d88322d62cb31b27a8bb9398f2dd8b79b8020fbea8d4ece056f3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Johannes-Krabbe/logf/releases/download/v#{version}/logf_#{version}_linux_amd64.tar.gz"
      sha256 "905d44f85f545078b180bc9ea0f425d87aa9f265c23357841f07e6b50797ca53"
    end
    on_arm do
      url "https://github.com/Johannes-Krabbe/logf/releases/download/v#{version}/logf_#{version}_linux_arm64.tar.gz"
      sha256 "6afa2c212b86e7119218119b031af7adf1e95ca76486ce5f361772acd1ed7ee5"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/logf"]
  end

  # No zap stanza required
end
