# This file was generated by GoReleaser. DO NOT EDIT.
cask "logf" do
  name "logf"
  desc "Interactive JSON log viewer for the terminal"
  homepage "https://github.com/Johannes-Krabbe/logf"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logf"

  on_macos do
    on_intel do
      url "https://github.com/Johannes-Krabbe/logf/releases/download/v#{version}/logf_#{version}_darwin_amd64.tar.gz"
      sha256 "73335c567799af14e21575354e3e1e50ad5c552a5f4174156997f3ec46fe9aab"
    end
    on_arm do
      url "https://github.com/Johannes-Krabbe/logf/releases/download/v#{version}/logf_#{version}_darwin_arm64.tar.gz"
      sha256 "e8b0e8902dc613eacae55aa0135ff901462be34f1a6ef52996b1bf99c16567f1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Johannes-Krabbe/logf/releases/download/v#{version}/logf_#{version}_linux_amd64.tar.gz"
      sha256 "6942ceae76bf5627567ff1b1995b1f3e1b488efe390d110100f0b60938459728"
    end
    on_arm do
      url "https://github.com/Johannes-Krabbe/logf/releases/download/v#{version}/logf_#{version}_linux_arm64.tar.gz"
      sha256 "a0588c3e67fd6cca9b5180a833831cdcda774078839222096463e19ae19bf1a4"
    end
  end

  # No zap stanza required
end
