# This file was generated by GoReleaser. DO NOT EDIT.
cask "twig" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "796474ec033a93eb3fc99a28fbf4901bc7bc7f6f890c985497ca5300c4254614"
      url "https://github.com/Johannes-Krabbe/twig/releases/download/v#{version}/twig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b065478a3029050b1d8011543616a2cc02682e4510d433ad3876ddbbb1295ad7"
      url "https://github.com/Johannes-Krabbe/twig/releases/download/v#{version}/twig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5f4c4bd16cf363f545639829ee81a359bc79921e1b957aeebc1ad9e4ab7f5e37"
      url "https://github.com/Johannes-Krabbe/twig/releases/download/v#{version}/twig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f2f55767f45910283f56b8bee49442cad220070e0bf869b9c54b5e2d3e5bddc1"
      url "https://github.com/Johannes-Krabbe/twig/releases/download/v#{version}/twig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "twig"
  desc "Manage git worktrees with one command"
  homepage "https://github.com/Johannes-Krabbe/twig"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twig"

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/twig"]
  end

  # No zap stanza required
end
